language: node_js
dist: bionic
node_js:
- 12
before_install:
- sudo apt-get -y install libssl1.1
- wget https://github.com/ForNeVeR/tdlib.native/releases/download/v1.6.0/tdlib.linux.zip
- sudo unzip tdlib.linux.zip -d /usr/lib/
- sudo chmod a+rw /usr/lib/libtdjson.so
after_success:
- "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
env:
  global:
    secure: qexOc2AiLhOUIr7BxQsBAXeCNHjalSs5LtNPLSznWZJFVkqUQLMkitHrh4vFvU0bpecZ5yZj2315c1woXw2X6HDyeyJg1R6dfZ5kSOWdhsK+K1iOP6TdDwDRga1Sh2Y2cFt64JPmuURE8ALEoB/muQxOebBf0sT9NfEC0Llv8D6FbrZzFIm5AVD5Cl6L0INm8fCVw5hba99AAwRotp8/DweSy5/nJ27hfNKI76jQAeEErN0HS+3LgnhSHumyyfmaipBI5opdK/Iond6qZ0/q1Svx3mc9leQpsPM4ZRQ+uyX2rFcTr974VMU3vgUc1LqZ9jKsaCrLtCNFdvvLREBRfBfDKbRSy6iUivX3xPuIbnPXPc0/YfXO0vLdh9eJ8Ktb/yFO30YMvrdVIMXdB5acMDCZP97hwb7avR3rnEZe9amKsnU9vwJdXNELxyinwNHYwKFsX0V7krNDF6HJF3ih06JxMorWF+436jtIO3bScjHgNtsCEE5NhXkDwDR3TncfYFHM624MSG084F5x2BBJTMopEAAG38spl3Ai17itOdbI8cVMSDFNIHSkGOQI/k3+jlEjDxqv5blgNwhA89n0ZUgA40B7OAreho2B1SHHX1IGZ2Hq9xQ5GFG1O0MkgxwB5eCXMMEGCVEX3tEeaOmNlkNao9WtAeCvovTk9i4khO8=
